# == Schema Information
# Schema version: 20101110123121
#
# Table name: SL_ACCOUNTS
#
#  CUCODE              :string(10)      primary key
#  CUNAME              :string(40)
#  CUADDRESS           :string(160)
#  CUPOSTCODE          :string(12)
#  CUPHONE             :string(20)
#  CUPHONE2            :string(20)
#  CUFAX               :string(20)
#  CUPROSCODE          :string(10)
#  CUCONTACT           :string(30)
#  CU_MULTI_CURR       :integer(3)      default(0)
#  CUSALUTE            :string(20)
#  CU_PRO_CONDATE      :datetime(23)
#  CU_EXPORT_CODE      :string(1)
#  CU_COUNTRY_CODE     :string(4)
#  CU_VAT_REG_NO       :string(21)
#  CU_EC_DELIVERY      :string(3)
#  CU_EC_T_NATURE      :string(2)
#  CU_EC_T_MODE        :string(1)
#  CUBALANCE           :decimal(, )     default(0.0)
#  CUBALANCE_C         :decimal(, )     default(0.0)
#  CUAGED_1            :decimal(, )     default(0.0)
#  CUAGED_2            :decimal(, )     default(0.0)
#  CUAGED_3            :decimal(, )     default(0.0)
#  CUAGED_4            :decimal(, )     default(0.0)
#  CUAGED_UNALLOC      :decimal(, )     default(0.0)
#  CUSORT              :string(20)
#  CUUSER1             :string(20)
#  CUUSER2             :string(20)
#  CUUSER3             :string(20)
#  CUUSED              :integer(3)      default(0)
#  CUTURNOVERPTD       :decimal(, )     default(0.0)
#  CUTURNOVR_L1        :decimal(, )     default(0.0)
#  CUTURNOVR_L2        :decimal(, )     default(0.0)
#  CUTURNOVR_L3        :decimal(, )     default(0.0)
#  CUTURNOVR_L4        :decimal(, )     default(0.0)
#  CUTURNOVR_L5        :decimal(, )     default(0.0)
#  CUTURNOVR_L6        :decimal(, )     default(0.0)
#  CUTURNOVR_L7        :decimal(, )     default(0.0)
#  CUTURNOVR_L8        :decimal(, )     default(0.0)
#  CUTURNOVR_L9        :decimal(, )     default(0.0)
#  CUTURNOVR_L10       :decimal(, )     default(0.0)
#  CUTURNOVR_L11       :decimal(, )     default(0.0)
#  CUTURNOVR_L12       :decimal(, )     default(0.0)
#  CUTURNOVR_L13       :decimal(, )     default(0.0)
#  CUTURNOVR_C1        :decimal(, )     default(0.0)
#  CUTURNOVR_C2        :decimal(, )     default(0.0)
#  CUTURNOVR_C3        :decimal(, )     default(0.0)
#  CUTURNOVR_C4        :decimal(, )     default(0.0)
#  CUTURNOVR_C5        :decimal(, )     default(0.0)
#  CUTURNOVR_C6        :decimal(, )     default(0.0)
#  CUTURNOVR_C7        :decimal(, )     default(0.0)
#  CUTURNOVR_C8        :decimal(, )     default(0.0)
#  CUTURNOVR_C9        :decimal(, )     default(0.0)
#  CUTURNOVR_C10       :decimal(, )     default(0.0)
#  CUTURNOVR_C11       :decimal(, )     default(0.0)
#  CUTURNOVR_C12       :decimal(, )     default(0.0)
#  CUTURNOVR_C13       :decimal(, )     default(0.0)
#  CUTURNOVR_O1        :decimal(, )     default(0.0)
#  CUTURNOVR_O2        :decimal(, )     default(0.0)
#  CUTURNOVR_O3        :decimal(, )     default(0.0)
#  CUTURNOVR_O4        :decimal(, )     default(0.0)
#  CUTURNOVR_O5        :decimal(, )     default(0.0)
#  CUTURNOVR_O6        :decimal(, )     default(0.0)
#  CUTURNOVR_O7        :decimal(, )     default(0.0)
#  CUTURNOVR_O8        :decimal(, )     default(0.0)
#  CUTURNOVR_O9        :decimal(, )     default(0.0)
#  CUTURNOVR_O10       :decimal(, )     default(0.0)
#  CUTURNOVR_O11       :decimal(, )     default(0.0)
#  CUTURNOVR_O12       :decimal(, )     default(0.0)
#  CUTURNOVR_O13       :decimal(, )     default(0.0)
#  CUTURNOVERYTD       :decimal(, )     default(0.0)
#  CUCURRENCYCODE      :string(4)
#  CUTURNOVR_L1_C      :decimal(, )     default(0.0)
#  CUTURNOVR_L2_C      :decimal(, )     default(0.0)
#  CUTURNOVR_L3_C      :decimal(, )     default(0.0)
#  CUTURNOVR_L4_C      :decimal(, )     default(0.0)
#  CUTURNOVR_L5_C      :decimal(, )     default(0.0)
#  CUTURNOVR_L6_C      :decimal(, )     default(0.0)
#  CUTURNOVR_L7_C      :decimal(, )     default(0.0)
#  CUTURNOVR_L8_C      :decimal(, )     default(0.0)
#  CUTURNOVR_L9_C      :decimal(, )     default(0.0)
#  CUTURNOVR_L10_C     :decimal(, )     default(0.0)
#  CUTURNOVR_L11_C     :decimal(, )     default(0.0)
#  CUTURNOVR_L12_C     :decimal(, )     default(0.0)
#  CUTURNOVR_L13_C     :decimal(, )     default(0.0)
#  CUTURNOVR_C1_C      :decimal(, )     default(0.0)
#  CUTURNOVR_C2_C      :decimal(, )     default(0.0)
#  CUTURNOVR_C3_C      :decimal(, )     default(0.0)
#  CUTURNOVR_C4_C      :decimal(, )     default(0.0)
#  CUTURNOVR_C5_C      :decimal(, )     default(0.0)
#  CUTURNOVR_C6_C      :decimal(, )     default(0.0)
#  CUTURNOVR_C7_C      :decimal(, )     default(0.0)
#  CUTURNOVR_C8_C      :decimal(, )     default(0.0)
#  CUTURNOVR_C9_C      :decimal(, )     default(0.0)
#  CUTURNOVR_C10_C     :decimal(, )     default(0.0)
#  CUTURNOVR_C11_C     :decimal(, )     default(0.0)
#  CUTURNOVR_C12_C     :decimal(, )     default(0.0)
#  CUTURNOVR_C13_C     :decimal(, )     default(0.0)
#  CUTURNOVR_O1_C      :decimal(, )     default(0.0)
#  CUTURNOVR_O2_C      :decimal(, )     default(0.0)
#  CUTURNOVR_O3_C      :decimal(, )     default(0.0)
#  CUTURNOVR_O4_C      :decimal(, )     default(0.0)
#  CUTURNOVR_O5_C      :decimal(, )     default(0.0)
#  CUTURNOVR_O6_C      :decimal(, )     default(0.0)
#  CUTURNOVR_O7_C      :decimal(, )     default(0.0)
#  CUTURNOVR_O8_C      :decimal(, )     default(0.0)
#  CUTURNOVR_O9_C      :decimal(, )     default(0.0)
#  CUTURNOVR_O10_C     :decimal(, )     default(0.0)
#  CUTURNOVR_O11_C     :decimal(, )     default(0.0)
#  CUTURNOVR_O12_C     :decimal(, )     default(0.0)
#  CUTURNOVR_O13_C     :decimal(, )     default(0.0)
#  CUTURNOVR_YTD_C     :decimal(, )     default(0.0)
#  CUTURNOVR_PTD_C     :decimal(, )     default(0.0)
#  CU_COSTVAL_1        :decimal(, )     default(0.0)
#  CU_COSTVAL_2        :decimal(, )     default(0.0)
#  CU_COSTVAL_3        :decimal(, )     default(0.0)
#  CU_COSTVAL_4        :decimal(, )     default(0.0)
#  CU_COSTVAL_5        :decimal(, )     default(0.0)
#  CU_COSTVAL_6        :decimal(, )     default(0.0)
#  CU_COSTVAL_7        :decimal(, )     default(0.0)
#  CU_COSTVAL_8        :decimal(, )     default(0.0)
#  CU_COSTVAL_9        :decimal(, )     default(0.0)
#  CU_COSTVAL_10       :decimal(, )     default(0.0)
#  CU_COSTVAL_11       :decimal(, )     default(0.0)
#  CU_COSTVAL_12       :decimal(, )     default(0.0)
#  CU_COSTVAL_13       :decimal(, )     default(0.0)
#  CU_SALEVAL_1        :decimal(, )     default(0.0)
#  CU_SALEVAL_2        :decimal(, )     default(0.0)
#  CU_SALEVAL_3        :decimal(, )     default(0.0)
#  CU_SALEVAL_4        :decimal(, )     default(0.0)
#  CU_SALEVAL_5        :decimal(, )     default(0.0)
#  CU_SALEVAL_6        :decimal(, )     default(0.0)
#  CU_SALEVAL_7        :decimal(, )     default(0.0)
#  CU_SALEVAL_8        :decimal(, )     default(0.0)
#  CU_SALEVAL_9        :decimal(, )     default(0.0)
#  CU_SALEVAL_10       :decimal(, )     default(0.0)
#  CU_COSTVAL_PTD      :decimal(, )     default(0.0)
#  CU_COSTVAL_YTD      :decimal(, )     default(0.0)
#  CU_SALEVAL_PTD      :decimal(, )     default(0.0)
#  CU_SALEVAL_YTD      :decimal(, )     default(0.0)
#  CU_COSTVALUE        :decimal(, )     default(0.0)
#  CU_SALEVALUE        :decimal(, )     default(0.0)
#  CU_SALEVAL_11       :decimal(, )     default(0.0)
#  CU_SALEVAL_12       :decimal(, )     default(0.0)
#  CU_SALEVAL_13       :decimal(, )     default(0.0)
#  CU_USERDATE1        :datetime(23)
#  CU_USERDATE2        :datetime(23)
#  CU_NOTES            :text
#  CU_MULTIADD_FLG     :integer(3)      default(0)
#  CU_INV_ADD_CDE      :decimal(, )     default(0.0)
#  CU_DEL_ADD_CDE      :decimal(, )     default(0.0)
#  CU_STAT_ADD_CDE     :decimal(, )     default(0.0)
#  CU_DATE_INV         :datetime(23)
#  CU_DATE_PAY         :datetime(23)
#  CU_USER_PUTIN       :string(4)
#  CU_DATE_PUTIN       :datetime(23)
#  CU_DATE_EDITED      :datetime(23)
#  CU_USER_EDITED      :string(4)
#  CU_MU_STATUS        :string(1)
#  CU_LINE_DISC        :decimal(, )     default(0.0)
#  CU_TOT_DISC         :decimal(, )     default(0.0)
#  CU_SETT_DISC_1      :decimal(, )     default(0.0)
#  CU_SETT_DISC_2      :decimal(, )     default(0.0)
#  CU_SETT_DAYS_1      :decimal(, )     default(0.0)
#  CU_SETT_DAYS_2      :decimal(, )     default(0.0)
#  CU_TERMS_OPTION     :decimal(, )     default(0.0)
#  CU_ON_STOP          :integer(3)      default(0)
#  CU_CREDIT_LIMIT     :decimal(, )     default(0.0)
#  CU_TERMS            :string(40)
#  CU_DEL_CHARGE       :decimal(, )     default(0.0)
#  CU_DEL_CHARGE_C     :decimal(, )     default(0.0)
#  CU_DEL_CHG_PCNT     :decimal(, )     default(0.0)
#  CU_MIN_ORDR         :decimal(, )     default(0.0)
#  CU_MIN_ORDR_C       :decimal(, )     default(0.0)
#  CU_DUE_DAYS         :decimal(, )     default(0.0)
#  CU_A_P_DAYS         :decimal(, )     default(0.0)
#  CU_DUEDATE_TYPE     :integer(3)      default(0)
#  CU_PRICE_KEY        :integer(3)      default(0)
#  CU_ANALYSIS         :string(25)
#  CU_TAX_CODE         :string(4)
#  CU_BANK_ANALYS      :string(25)
#  CU_INV_LAYOUT       :string(255)
#  CU_PRIMARY          :decimal(, )     not null
#  CU_DEALERCODE       :string(10)
#  CU_ADDRESS_USER1    :string(30)
#  CU_ADDRESS_USER2    :string(30)
#  CU_EMAIL            :string(64)
#  CU_WEB_PASSWORD     :string(10)
#  CU_CURRENCY_CHANGED :integer(3)      default(0)
#  CU_SOURCE           :string(1)
#  CU_ACCOUNT_TYPE     :string(1)
#  CU_DOC_DESTINATION  :string(10)
#  CU_COUNTRY          :string(35)
#  CU_DO_NOT_USE       :boolean         not null
#

class Customer < ActiveRecord::Base
  use_connection_ninja(:mssql)
  set_table_name 'SL_ACCOUNTS'
  set_primary_key 'CUCODE'

  alias_attribute "id", "CUCODE"
  alias_attribute "postcode", "CUPOSTCODE"

end
